channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - azureml-mlflow==1.38.0
      - azureml-sdk==1.38.0
      - scikit-learn==1.5.2
      - pandas==2.2.3
      - torch==2.5.1
      - flask==3.0.3
      - numpy==2.1.3
